### ISSUE TITLE
Implement the bump command

### ISSUE THREAD

**Issue by keithjiff** [keithjiff/bifurcate#2]
### Assumptions
* `bifurcate` is being run from the root `jiff-ios` folder

### Tasks
- [ ] Change to current release branch
- [ ] Pull the latest code
- [ ] Create & switch to new branch for next release
- [ ] Push new branch to repo
- [ ] Create a `WELL-0000` branch locally
- [ ] Update the Jiff project's `Info.plist` file with the new version number
  * use `PlistBuddy` to accomplish this
- [ ] Commit that change
- [ ] Push commit up to repo
