### ISSUE TITLE
Capture path-to-working-directory (pwd)

### ISSUE THREAD

**Issue by keithjiff** [keithjiff/bifurcate#3]
### Tasks
- [ ] Pull the `pwd` code from `JiffDevTools`
- [ ] Add `workingFolder` to `ReleaseInfo`
- [ ] Automatically detect the `pwd` at launch time

**Comment by keithjiff** [comment]
### Questions
* What to do if the auto-detected `pwd` is different from the stored one?

**Comment by keithjiff** [comment]
I don't believe this is necessary. We'll just assume that `bifurcate` is being run from the root folder of the `jiff-ios` project.

Marking this closed; reopen if this feature is needed.
