### ISSUE TITLE
Prepare for bump command

### ISSUE THREAD

**Issue by keithjiff** [keithjiff/bifurcate#4]
Before the `bump` command can be implemented a few preliminary tasks need to be completed.

### Tasks
- [x] In `App`,  move `releaseInfo?.save()` from `run()` to `onUpdateReleaseNumber(package:)`
- [x] Remove unnecessary logging
  - [x] Bring in `Log` from `JiffDevTools`
  - [x] If no arguments provided on command line, just display the current `ReleaseInfo` values.
  - [x] Provide means for turning logging on off (i.e. `bifurcate logging:on`)

**Comment by keithjiff** [comment]
Commits 7651455, 95afdf2, fd21885, e0380c0 cover this.
